---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwanak-bnb-server
  labels:
    app: gwanak-bnb-server
  namespace: <NAMESPACE>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gwanak-bnb-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: gwanak-bnb-server
    spec:
      serviceAccountName: gwanak-bnb-server-sa
      nodeSelector:
        kubernetes.io/arch: <ARCH>
        phase: prod
      tolerations:
        - effect: NoSchedule
          key: phase
          operator: Equal
          value: prod
      containers:
        - image: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/<ECR_REPO>:<IMAGE_TAG>
          name: gwanak-bnb-server
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://<RDS_ENDPOINT>:3306/<DB_NAME>?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "<DB_USERNAME>"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "<DB_PASSWORD>"
            - name: JWT_SECRET
              value: "<JWT_SECRET>"
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 750Mi
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gwanak-bnb-server-sa
  namespace: <NAMESPACE>
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<IAM_ROLE_NAME>
---
apiVersion: v1
kind: Service
metadata:
  namespace: <NAMESPACE>
  name: gwanak-bnb-server
spec:
  type: ClusterIP
  selector:
    app: gwanak-bnb-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: <NAMESPACE>
  name: gwanak-bnb-server
spec:
  gateways:
    - <ISTIO_GATEWAY>
    - mesh
  hosts:
    - <API_HOSTNAME>
  http:
    - route:
        - destination:
            host: gwanak-bnb-server